export const MODAL_STATE = "MODAL_STATE"
export const INTERVIEW_STATE = "INTERVIEW_STATE"
export const ACCESS_TOKEN = "ACCESS_TOKEN"
export const GET_CHAT = 'GET_CHAT'
export const GET_CHAT_SUCCESS = 'GET_CHAT_SUCCESS'
export const GET_CHAT_ERROR = 'GET_CHAT_ERROR'